### ISSUE TITLE
[Go项目实战]

### ISSUE THREAD

**Issue by Yefangbiao** [jiujuan/go-collection#2]
[Go项目实战]里面的go小项目实战没有资源了

**Comment by jiujuan** [comment]
@Yefangbiao 

> [Go项目实战]里面的go小项目实战没有资源了

确实是的，作者好像是关了，我换了一个学习的系列 [https://www.jianshu.com/nb/40576814](https://www.jianshu.com/nb/40576814)。

ths

**Comment by jiujuan** [comment]
我已经换了一个go实战的地址了
