### ISSUE TITLE
About Your Readme File

### ISSUE THREAD

**Issue by zzdpk2** [jiujuan/go-collection#3]
Hi,
It seems your image in the readme files is unavailable. Could you update your image? 
Thanks

**Comment by jiujuan** [comment]
> 
> 
> Hi,
> It seems your image in the readme files is unavailable. Could you update your image?
> Thanks

which one？the image is all in the github？

**Comment by jiujuan** [comment]
> 
> 
> Hi,
> It seems your image in the readme files is unavailable. Could you update your image?
> Thanks

which one？ all images are on the github.com？
