### ISSUE TITLE
go语言高级特性学习   return 404

### ISSUE THREAD

**Issue by tablecell** [jiujuan/go-collection#4]
go语言基础学习 https://blog.csdn.net/u010986776/category_8000832.html
go语言高级特性学习 https://blog.csdn.net/u010986776/article/category/8004337

**Comment by jiujuan** [comment]
额，变成收费了，我找找其它go方面的学习换一下

> go语言基础学习 https://blog.csdn.net/u010986776/category_8000832.html go语言高级特性学习 https://blog.csdn.net/u010986776/article/category/8004337
